name: Feature Request
description: Suggest a new feature or enhancement for Kuysor
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible about your use case and proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe the specific use case or scenario where this feature would be helpful.
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: "I think it would be great if..."
    validations:
      required: true

  - type: textarea
    id: api_example
    attributes:
      label: Proposed API
      description: If applicable, show how you envision the API would look like
      render: go
      placeholder: |
        // Example of how the new feature would be used
        ks, err := kuysor.
            NewQuery("SELECT * FROM users").
            WithNewFeature(...).
            Build()

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: "Alternatively, we could..."

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or references about the feature request here.
      placeholder: "This feature would be similar to..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve my workflow"
        - "High - Critical for my use case"
    validations:
      required: true

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility
      description: Please consider the following
      options:
        - label: This feature should maintain backward compatibility
        - label: This feature could introduce breaking changes (if necessary)
        - label: This feature aligns with the zero-dependency principle

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this feature hasn't been requested
          required: true
        - label: I have provided a clear use case for this feature
          required: true
        - label: I understand this is a request and not a guarantee of implementation
          required: true 